<?php

namespace Database\Seeders;

use App\Models\EducationLevel;
use App\Models\School;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class HaNamSchoolsSeeder extends Seeder
{
    public function run(): void
    {
        $schools = [
            // ==============================================================
            // CÁC TRƯỜNG TẠI HÀ NAM
            // ==============================================================
            [
                'id' => 'HN-CD-001',
                'code' => '37101',
                'name' => 'Trường Cao đẳng FPT Polytechnic cơ sở Hà Nam',
                'education_level_id' => 'cao_dang',
                'school_type_id' => 'tu_thuc',
                'ward' => 'Phường Hà Nam',
                'legacy_province' => 'Hà Nam',
                'address' => 'Đường Độc Lập, KĐT Đại học Nam Cao, Thị xã Duy Tiên, Tỉnh Hà Nam',
                'lat' => 20.607146,
                'lng' => 105.932884,
                'phone' => '0226 730 0999',
                'email' => 'caodangfpt.hn@fpt.edu.vn',
                'website' => 'https://caodang.fpt.edu.vn',
                'principal' => 'Vũ Chí Thành',
                'leaders' => [
                    ['name' => 'Vũ Chí Thành', 'position' => 'Hiệu trưởng'],
                    ['name' => 'Trần Hữu Thiện', 'position' => 'Giám đốc cơ sở Hà Nam'],
                    ['name' => 'Nguyễn Thị Kim Loan', 'position' => 'Trưởng ban Đào tạo']
                ],
                'training_majors' => [
                    ['name' => 'Công nghệ thông tin', 'degree_level' => 'cao_dang', 'major_code' => '6480201', 'annual_quota' => 500],
                    ['name' => 'Thiết kế đồ họa', 'degree_level' => 'cao_dang', 'major_code' => '6210403', 'annual_quota' => 300],
                    ['name' => 'Tự động hóa & Kỹ thuật điều khiển', 'degree_level' => 'cao_dang', 'major_code' => '6520216', 'annual_quota' => 250],
                    ['name' => 'Kinh tế & Digital Marketing', 'degree_level' => 'cao_dang', 'major_code' => '6340115', 'annual_quota' => 400]
                ],
                'is_national_standard' => true,
                'national_standard_level' => 2,
                'founded_year' => 2021,
                'student_count' => 2200,
                'annual_enrollment' => 1200,
                'annual_graduates' => 950,
                'employment_rate' => 97.5,
                'teacher_count' => 95,
                'teacher_quota' => 100,
                'teachers_shortage' => 5,
                'teachers_surplus' => 0,
                'faculty_rank_1' => 15,
                'faculty_rank_2' => 30,
                'faculty_rank_3' => 50,
                'faculty_doctors' => 8,
                'faculty_masters' => 62,
                'faculty_professors' => 1,
                'class_count' => 50,
                'classroom_count' => 45,
                'computer_room_count' => 10,
                'library' => true,
                'lab_count' => 8,
                'workshops_count' => 6,
                'campus_area_m2' => 25000,
                'partner_enterprises' => [
                    ['name' => 'Tập đoàn FPT', 'cooperation' => 'Hợp tác tuyển dụng và đào tạo kỹ sư công nghệ', 'logo' => 'https://images.unsplash.com/photo-1549399542-7e3f8b79c341?w=200&auto=format&fit=crop&q=80', 'is_featured' => true],
                    ['name' => 'FPT Software', 'cooperation' => 'Thực tập sinh dự án và bảo đảm việc làm sau tốt nghiệp', 'logo' => 'https://images.unsplash.com/photo-1581091226825-a6a2a5aee158?w=200&auto=format&fit=crop&q=80', 'is_featured' => true],
                    ['name' => 'Viettel Hà Nam', 'cooperation' => 'Tài trợ thiết bị mạng viễn thông thực hành', 'logo' => 'https://images.unsplash.com/photo-1504917599217-d4dc5ebe6122?w=200&auto=format&fit=crop&q=80', 'is_featured' => true]
                ],
                'gallery' => [
                    'https://images.unsplash.com/photo-1562774053-701939374585?w=800&auto=format&fit=crop&q=80',
                    'https://images.unsplash.com/photo-1523240795612-9a054b0db644?w=800&auto=format&fit=crop&q=80',
                    'https://images.unsplash.com/photo-1541339907198-e08756dedf3f?w=800&auto=format&fit=crop&q=80'
                ],
                'status' => 'VERIFIED'
            ],
            [
                'id' => 'HN-DH-001',
                'code' => '37102',
                'name' => 'Trường Đại học Công nghiệp Hà Nội (Cơ sở Hà Nam)',
                'education_level_id' => 'dai_hoc',
                'school_type_id' => 'cong_lap',
                'ward' => 'Phường Phù Vân',
                'legacy_province' => 'Hà Nam',
                'address' => 'Đường Lê Hồng Phong, Phường Phù Vân, Tỉnh Hà Nam',
                'lat' => 20.547120,
                'lng' => 105.908250,
                'phone' => '0226 385 1004',
                'email' => 'haui.hanam@haui.edu.vn',
                'website' => 'https://www.haui.edu.vn',
                'principal' => 'TS. Kiều Xuân Thực',
                'leaders' => [
                    ['name' => 'TS. Kiều Xuân Thực', 'position' => 'Hiệu trưởng'],
                    ['name' => 'PGS.TS. Phạm Văn Đông', 'position' => 'Phó Hiệu trưởng phụ trách cơ sở'],
                    ['name' => 'TS. Nguyễn Văn Thiện', 'position' => 'Trưởng phòng Đào tạo']
                ],
                'training_majors' => [
                    ['name' => 'Công nghệ Kỹ thuật Cơ khí', 'degree_level' => 'dai_hoc', 'major_code' => '7520103', 'annual_quota' => 600],
                    ['name' => 'Công nghệ Kỹ thuật Ô tô', 'degree_level' => 'dai_hoc', 'major_code' => '7520130', 'annual_quota' => 550],
                    ['name' => 'Công nghệ Thông tin', 'degree_level' => 'dai_hoc', 'major_code' => '7480201', 'annual_quota' => 500],
                    ['name' => 'Kỹ thuật Điện - Điện tử', 'degree_level' => 'dai_hoc', 'major_code' => '7520201', 'annual_quota' => 450]
                ],
                'is_national_standard' => true,
                'national_standard_level' => 2,
                'founded_year' => 1898,
                'student_count' => 6500,
                'annual_enrollment' => 2500,
                'annual_graduates' => 2100,
                'employment_rate' => 96.0,
                'teacher_count' => 280,
                'teacher_quota' => 300,
                'teachers_shortage' => 20,
                'teachers_surplus' => 0,
                'faculty_rank_1' => 45,
                'faculty_rank_2' => 85,
                'faculty_rank_3' => 150,
                'faculty_doctors' => 65,
                'faculty_masters' => 195,
                'faculty_professors' => 8,
                'class_count' => 140,
                'classroom_count' => 120,
                'computer_room_count' => 16,
                'library' => true,
                'lab_count' => 25,
                'workshops_count' => 18,
                'campus_area_m2' => 110000,
                'partner_enterprises' => [
                    ['name' => 'Công ty Honda Việt Nam', 'cooperation' => 'Hợp tác chuyển giao công nghệ ô tô và xe máy', 'logo' => 'https://images.unsplash.com/photo-1549399542-7e3f8b79c341?w=200&auto=format&fit=crop&q=80', 'is_featured' => true],
                    ['name' => 'Samsung Electronics Việt Nam', 'cooperation' => 'Tài trợ phòng Lab tự động hóa và tuyển dụng kỹ sư', 'logo' => 'https://images.unsplash.com/photo-1581091226825-a6a2a5aee158?w=200&auto=format&fit=crop&q=80', 'is_featured' => true]
                ],
                'gallery' => [
                    'https://images.unsplash.com/photo-1562774053-701939374585?w=800&auto=format&fit=crop&q=80',
                    'https://images.unsplash.com/photo-1581092160607-ee22621dd758?w=800&auto=format&fit=crop&q=80'
                ],
                'status' => 'VERIFIED'
            ],
            [
                'id' => 'HN-DH-002',
                'code' => '37103',
                'name' => 'Trường Đại học Thương mại (Cơ sở Hà Nam)',
                'education_level_id' => 'dai_hoc',
                'school_type_id' => 'cong_lap',
                'ward' => 'Phường Liêm Tuyền',
                'legacy_province' => 'Hà Nam',
                'address' => 'Đường Lý Thường Kiệt, Phường Liêm Tuyền, TP. Phủ Lý, Tỉnh Hà Nam',
                'lat' => 20.528540,
                'lng' => 105.942120,
                'phone' => '0226 385 2779',
                'email' => 'cosohanam@tmu.edu.vn',
                'website' => 'https://hanam.tmu.edu.vn',
                'principal' => 'PGS.TS. Nguyễn Hoàng',
                'leaders' => [
                    ['name' => 'PGS.TS. Nguyễn Hoàng', 'position' => 'Hiệu trưởng'],
                    ['name' => 'TS. Đinh Thị Lan', 'position' => 'Giám đốc Cơ sở Hà Nam']
                ],
                'training_majors' => [
                    ['name' => 'Logistics & Quản lý Chuỗi cung ứng', 'degree_level' => 'dai_hoc', 'major_code' => '7510605', 'annual_quota' => 400],
                    ['name' => 'Thương mại Điện tử', 'degree_level' => 'dai_hoc', 'major_code' => '7340122', 'annual_quota' => 350],
                    ['name' => 'Quản trị Khách sạn - Du lịch', 'degree_level' => 'dai_hoc', 'major_code' => '7810201', 'annual_quota' => 300],
                    ['name' => 'Kế toán Doanh nghiệp', 'degree_level' => 'dai_hoc', 'major_code' => '7340301', 'annual_quota' => 350]
                ],
                'is_national_standard' => true,
                'national_standard_level' => 2,
                'founded_year' => 1960,
                'student_count' => 3800,
                'annual_enrollment' => 1500,
                'annual_graduates' => 1300,
                'employment_rate' => 95.5,
                'teacher_count' => 165,
                'teacher_quota' => 175,
                'teachers_shortage' => 10,
                'teachers_surplus' => 0,
                'faculty_rank_1' => 25,
                'faculty_rank_2' => 50,
                'faculty_rank_3' => 90,
                'faculty_doctors' => 42,
                'faculty_masters' => 115,
                'faculty_professors' => 5,
                'class_count' => 85,
                'classroom_count' => 75,
                'computer_room_count' => 8,
                'library' => true,
                'lab_count' => 6,
                'workshops_count' => 4,
                'campus_area_m2' => 65000,
                'partner_enterprises' => [
                    ['name' => 'Tập đoàn Vingroup', 'cooperation' => 'Hợp tác đào tạo và tuyển dụng ngành bán lẻ & du lịch', 'logo' => 'https://images.unsplash.com/photo-1504917599217-d4dc5ebe6122?w=200&auto=format&fit=crop&q=80', 'is_featured' => true]
                ],
                'gallery' => [
                    'https://images.unsplash.com/photo-1523240795612-9a054b0db644?w=800&auto=format&fit=crop&q=80',
                    'https://images.unsplash.com/photo-1541339907198-e08756dedf3f?w=800&auto=format&fit=crop&q=80'
                ],
                'status' => 'VERIFIED'
            ],
            [
                'id' => 'HN-DH-003',
                'code' => '37104',
                'name' => 'Trường Đại học Sư phạm Hà Nội (Cơ sở Hà Nam)',
                'education_level_id' => 'dai_hoc',
                'school_type_id' => 'cong_lap',
                'ward' => 'Phường Phủ Lý',
                'legacy_province' => 'Hà Nam',
                'address' => 'Đường Lý Thường Kiệt, Phường Lam Hạ, TP. Phủ Lý, Tỉnh Hà Nam',
                'lat' => 20.541280,
                'lng' => 105.923450,
                'phone' => '0226 385 2888',
                'email' => 'hnue.hanam@hnue.edu.vn',
                'website' => 'https://hnue.edu.vn',
                'principal' => 'GS.TS. Nguyễn Văn Minh',
                'leaders' => [
                    ['name' => 'GS.TS. Nguyễn Văn Minh', 'position' => 'Hiệu trưởng'],
                    ['name' => 'PGS.TS. Nguyễn Đức Sơn', 'position' => 'Phó Hiệu trưởng']
                ],
                'training_majors' => [
                    ['name' => 'Sư phạm Toán học', 'degree_level' => 'dai_hoc', 'major_code' => '7140209', 'annual_quota' => 200],
                    ['name' => 'Sư phạm Ngữ văn', 'degree_level' => 'dai_hoc', 'major_code' => '7140217', 'annual_quota' => 200],
                    ['name' => 'Giáo dục Mầm non & Tiểu học', 'degree_level' => 'dai_hoc', 'major_code' => '7140202', 'annual_quota' => 350],
                    ['name' => 'Sư phạm Tiếng Anh', 'degree_level' => 'dai_hoc', 'major_code' => '7140231', 'annual_quota' => 250]
                ],
                'is_national_standard' => true,
                'national_standard_level' => 2,
                'founded_year' => 1951,
                'student_count' => 2900,
                'annual_enrollment' => 1100,
                'annual_graduates' => 950,
                'employment_rate' => 94.0,
                'teacher_count' => 140,
                'teacher_quota' => 150,
                'teachers_shortage' => 10,
                'teachers_surplus' => 0,
                'faculty_rank_1' => 30,
                'faculty_rank_2' => 45,
                'faculty_rank_3' => 65,
                'faculty_doctors' => 48,
                'faculty_masters' => 85,
                'faculty_professors' => 6,
                'class_count' => 70,
                'classroom_count' => 65,
                'computer_room_count' => 6,
                'library' => true,
                'lab_count' => 8,
                'workshops_count' => 3,
                'campus_area_m2' => 52000,
                'partner_enterprises' => [],
                'gallery' => [
                    'https://images.unsplash.com/photo-1562774053-701939374585?w=800&auto=format&fit=crop&q=80'
                ],
                'status' => 'VERIFIED'
            ],
            [
                'id' => 'HN-DH-004',
                'code' => '37105',
                'name' => 'Trường Đại học Tài chính - Ngân hàng Hà Nội (Cơ sở Nam Cao)',
                'education_level_id' => 'dai_hoc',
                'school_type_id' => 'tu_thuc',
                'ward' => 'Phường Hà Nam',
                'legacy_province' => 'Hà Nam',
                'address' => 'Khu Đô thị Đại học Nam Cao, Thị xã Duy Tiên, Tỉnh Hà Nam',
                'lat' => 20.612050,
                'lng' => 105.934020,
                'phone' => '024 3793 1340',
                'email' => 'fbu.hanam@fbu.edu.vn',
                'website' => 'https://fbu.edu.vn',
                'principal' => 'PGS.TS. Bùi Xuân Hải',
                'leaders' => [
                    ['name' => 'PGS.TS. Bùi Xuân Hải', 'position' => 'Hiệu trưởng'],
                    ['name' => 'TS. Phạm Văn Huấn', 'position' => 'Phó Hiệu trưởng']
                ],
                'training_majors' => [
                    ['name' => 'Tài chính - Ngân hàng', 'degree_level' => 'dai_hoc', 'major_code' => '7340201', 'annual_quota' => 450],
                    ['name' => 'Quản trị Kinh doanh', 'degree_level' => 'dai_hoc', 'major_code' => '7340101', 'annual_quota' => 400],
                    ['name' => 'Kế toán - Kiểm toán', 'degree_level' => 'dai_hoc', 'major_code' => '7340302', 'annual_quota' => 350]
                ],
                'is_national_standard' => true,
                'national_standard_level' => 1,
                'founded_year' => 2010,
                'student_count' => 2100,
                'annual_enrollment' => 900,
                'annual_graduates' => 750,
                'employment_rate' => 93.5,
                'teacher_count' => 90,
                'teacher_quota' => 95,
                'teachers_shortage' => 5,
                'teachers_surplus' => 0,
                'faculty_rank_1' => 15,
                'faculty_rank_2' => 30,
                'faculty_rank_3' => 45,
                'faculty_doctors' => 22,
                'faculty_masters' => 64,
                'faculty_professors' => 2,
                'class_count' => 50,
                'classroom_count' => 45,
                'computer_room_count' => 6,
                'library' => true,
                'lab_count' => 4,
                'workshops_count' => 2,
                'campus_area_m2' => 45000,
                'partner_enterprises' => [],
                'gallery' => [
                    'https://images.unsplash.com/photo-1523240795612-9a054b0db644?w=800&auto=format&fit=crop&q=80'
                ],
                'status' => 'VERIFIED'
            ],
            [
                'id' => 'HN-CD-002',
                'code' => '37106',
                'name' => 'Trường Cao đẳng Y tế Hà Nam',
                'education_level_id' => 'cao_dang',
                'school_type_id' => 'cong_lap',
                'ward' => 'Phường Phủ Lý',
                'legacy_province' => 'Hà Nam',
                'address' => 'Số 56 Nguyễn Du, Phường Hai Bà Trưng, TP. Phủ Lý, Tỉnh Hà Nam',
                'lat' => 20.536550,
                'lng' => 105.918220,
                'phone' => '0226 385 2736',
                'email' => 'cdythanam@gmail.com',
                'website' => 'http://cdyt-hanam.edu.vn',
                'principal' => 'BSCKII. Đinh Khắc Hậu',
                'leaders' => [
                    ['name' => 'BSCKII. Đinh Khắc Hậu', 'position' => 'Hiệu trưởng'],
                    ['name' => 'BSCKII. Trương Thị Thanh', 'position' => 'Phó Hiệu trưởng']
                ],
                'training_majors' => [
                    ['name' => 'Dược sĩ Cao đẳng', 'degree_level' => 'cao_dang', 'major_code' => '6720201', 'annual_quota' => 300],
                    ['name' => 'Điều dưỡng Đa khoa', 'degree_level' => 'cao_dang', 'major_code' => '6720301', 'annual_quota' => 350],
                    ['name' => 'Hộ sinh & Y sĩ Đa khoa', 'degree_level' => 'cao_dang', 'major_code' => '6720101', 'annual_quota' => 200],
                    ['name' => 'Kỹ thuật Xét nghiệm Y học', 'degree_level' => 'cao_dang', 'major_code' => '6720602', 'annual_quota' => 150]
                ],
                'is_national_standard' => true,
                'national_standard_level' => 2,
                'founded_year' => 1968,
                'student_count' => 1850,
                'annual_enrollment' => 850,
                'annual_graduates' => 780,
                'employment_rate' => 96.2,
                'teacher_count' => 105,
                'teacher_quota' => 110,
                'teachers_shortage' => 5,
                'teachers_surplus' => 0,
                'faculty_rank_1' => 18,
                'faculty_rank_2' => 32,
                'faculty_rank_3' => 55,
                'faculty_doctors' => 15,
                'faculty_masters' => 72,
                'faculty_professors' => 1,
                'class_count' => 45,
                'classroom_count' => 40,
                'computer_room_count' => 4,
                'library' => true,
                'lab_count' => 12,
                'workshops_count' => 5,
                'campus_area_m2' => 28000,
                'partner_enterprises' => [
                    ['name' => 'Bệnh viện Đa khoa Tỉnh Hà Nam', 'cooperation' => 'Bệnh viện thực hành lâm sàng chính cho sinh viên', 'logo' => 'https://images.unsplash.com/photo-1581091226825-a6a2a5aee158?w=200&auto=format&fit=crop&q=80', 'is_featured' => true],
                    ['name' => 'Bệnh viện Bạch Mai (Cơ sở 2)', 'cooperation' => 'Hợp tác đào tạo điều dưỡng chuyên khoa sâu', 'logo' => 'https://images.unsplash.com/photo-1504917599217-d4dc5ebe6122?w=200&auto=format&fit=crop&q=80', 'is_featured' => true]
                ],
                'gallery' => [
                    'https://images.unsplash.com/photo-1581092160607-ee22621dd758?w=800&auto=format&fit=crop&q=80'
                ],
                'status' => 'VERIFIED'
            ],
            [
                'id' => 'HN-CD-003',
                'code' => '37107',
                'name' => 'Trường Cao đẳng Nghề Hà Nam',
                'education_level_id' => 'cao_dang',
                'school_type_id' => 'cong_lap',
                'ward' => 'Phường Tiên Sơn',
                'legacy_province' => 'Hà Nam',
                'address' => 'Phường Đồng Văn, Thị xã Duy Tiên, Tỉnh Hà Nam',
                'lat' => 20.635220,
                'lng' => 105.941850,
                'phone' => '0226 383 5144',
                'email' => 'cdnhanam@gmail.com',
                'website' => 'http://cdnhanam.edu.vn',
                'principal' => 'ThS. Vũ Hữu Ý',
                'leaders' => [
                    ['name' => 'ThS. Vũ Hữu Ý', 'position' => 'Hiệu trưởng'],
                    ['name' => 'ThS. Lại Văn Vĩnh', 'position' => 'Phó Hiệu trưởng']
                ],
                'training_majors' => [
                    ['name' => 'Cắt gọt kim loại CNC', 'degree_level' => 'cao_dang', 'major_code' => '6520121', 'annual_quota' => 250],
                    ['name' => 'Hàn công nghệ cao', 'degree_level' => 'cao_dang', 'major_code' => '6520123', 'annual_quota' => 200],
                    ['name' => 'Điện công nghiệp & Tự động hóa', 'degree_level' => 'cao_dang', 'major_code' => '6520227', 'annual_quota' => 220],
                    ['name' => 'Công nghệ Kỹ thuật Ô tô', 'degree_level' => 'cao_dang', 'major_code' => '6510216', 'annual_quota' => 200]
                ],
                'is_national_standard' => true,
                'national_standard_level' => 2,
                'founded_year' => 2007,
                'student_count' => 1600,
                'annual_enrollment' => 800,
                'annual_graduates' => 720,
                'employment_rate' => 95.0,
                'teacher_count' => 85,
                'teacher_quota' => 90,
                'teachers_shortage' => 5,
                'teachers_surplus' => 0,
                'faculty_rank_1' => 12,
                'faculty_rank_2' => 28,
                'faculty_rank_3' => 45,
                'faculty_doctors' => 6,
                'faculty_masters' => 58,
                'faculty_professors' => 0,
                'class_count' => 42,
                'classroom_count' => 38,
                'computer_room_count' => 5,
                'library' => true,
                'lab_count' => 8,
                'workshops_count' => 12,
                'campus_area_m2' => 36000,
                'partner_enterprises' => [
                    ['name' => 'Công ty TNHH YKK Việt Nam (KCN Đồng Văn)', 'cooperation' => 'Hợp tác tuyển dụng kỹ thuật viên cơ khí', 'logo' => 'https://images.unsplash.com/photo-1549399542-7e3f8b79c341?w=200&auto=format&fit=crop&q=80', 'is_featured' => true]
                ],
                'gallery' => [
                    'https://images.unsplash.com/photo-1581092335397-9583fe92d232?w=800&auto=format&fit=crop&q=80'
                ],
                'status' => 'VERIFIED'
            ],
            [
                'id' => 'HN-CD-004',
                'code' => '37108',
                'name' => 'Trường Cao đẳng Phát thanh - Truyền hình I (VOV)',
                'education_level_id' => 'cao_dang',
                'school_type_id' => 'cong_lap',
                'ward' => 'Phường Phủ Lý',
                'legacy_province' => 'Hà Nam',
                'address' => 'Số 136 đường Quy Lưu, Phường Minh Khai, TP. Phủ Lý, Tỉnh Hà Nam',
                'lat' => 20.539820,
                'lng' => 105.914210,
                'phone' => '0226 385 2772',
                'email' => 'ptth1@vov.vn',
                'website' => 'http://edu.vov.vn',
                'principal' => 'TS. Nguyễn Văn Sơn',
                'leaders' => [
                    ['name' => 'TS. Nguyễn Văn Sơn', 'position' => 'Hiệu trưởng'],
                    ['name' => 'ThS. Nguyễn Thị Mai', 'position' => 'Phó Hiệu trưởng']
                ],
                'training_majors' => [
                    ['name' => 'Báo chí Truyền hình', 'degree_level' => 'cao_dang', 'major_code' => '6320101', 'annual_quota' => 250],
                    ['name' => 'Quay phim & Nhiếp ảnh', 'degree_level' => 'cao_dang', 'major_code' => '6210202', 'annual_quota' => 150],
                    ['name' => 'Đồ họa Truyền thông Đa phương tiện', 'degree_level' => 'cao_dang', 'major_code' => '6210403', 'annual_quota' => 200],
                    ['name' => 'Kỹ thuật Điện tử Viễn thông', 'degree_level' => 'cao_dang', 'major_code' => '6520207', 'annual_quota' => 180]
                ],
                'is_national_standard' => true,
                'national_standard_level' => 2,
                'founded_year' => 1956,
                'student_count' => 1450,
                'annual_enrollment' => 700,
                'annual_graduates' => 640,
                'employment_rate' => 93.0,
                'teacher_count' => 78,
                'teacher_quota' => 85,
                'teachers_shortage' => 7,
                'teachers_surplus' => 0,
                'faculty_rank_1' => 10,
                'faculty_rank_2' => 25,
                'faculty_rank_3' => 43,
                'faculty_doctors' => 8,
                'faculty_masters' => 55,
                'faculty_professors' => 1,
                'class_count' => 38,
                'classroom_count' => 35,
                'computer_room_count' => 6,
                'library' => true,
                'lab_count' => 6,
                'workshops_count' => 4,
                'campus_area_m2' => 32000,
                'partner_enterprises' => [
                    ['name' => 'Đài Tiếng nói Việt Nam (VOV)', 'cooperation' => 'Cơ quan chủ quản - thực tập và làm việc tại các kênh phát thanh truyền hình', 'logo' => 'https://images.unsplash.com/photo-1549399542-7e3f8b79c341?w=200&auto=format&fit=crop&q=80', 'is_featured' => true]
                ],
                'gallery' => [
                    'https://images.unsplash.com/photo-1562774053-701939374585?w=800&auto=format&fit=crop&q=80'
                ],
                'status' => 'VERIFIED'
            ],
            [
                'id' => 'HN-CD-005',
                'code' => '37109',
                'name' => 'Trường Cao đẳng Thủy lợi Bắc Bộ',
                'education_level_id' => 'cao_dang',
                'school_type_id' => 'cong_lap',
                'ward' => 'Phường Phù Vân',
                'legacy_province' => 'Hà Nam',
                'address' => 'Xã Phù Vân, TP. Phủ Lý, Tỉnh Hà Nam',
                'lat' => 20.550150,
                'lng' => 105.911040,
                'phone' => '0226 385 2769',
                'email' => 'cdthuyloibb@gmail.com',
                'website' => 'http://tlbb.edu.vn',
                'principal' => 'ThS. Phạm Gia Điệp',
                'leaders' => [
                    ['name' => 'ThS. Phạm Gia Điệp', 'position' => 'Hiệu trưởng'],
                    ['name' => 'ThS. Trần Văn Kiên', 'position' => 'Phó Hiệu trưởng']
                ],
                'training_majors' => [
                    ['name' => 'Xây dựng Công trình Thủy lợi', 'degree_level' => 'cao_dang', 'major_code' => '6580202', 'annual_quota' => 200],
                    ['name' => 'Quản lý Tài nguyên Nước & Môi trường', 'degree_level' => 'cao_dang', 'major_code' => '6850101', 'annual_quota' => 150],
                    ['name' => 'Trắc địa Bản đồ & Địa chính', 'degree_level' => 'cao_dang', 'major_code' => '6520501', 'annual_quota' => 180]
                ],
                'is_national_standard' => true,
                'national_standard_level' => 1,
                'founded_year' => 1967,
                'student_count' => 1200,
                'annual_enrollment' => 550,
                'annual_graduates' => 490,
                'employment_rate' => 91.0,
                'teacher_count' => 65,
                'teacher_quota' => 70,
                'teachers_shortage' => 5,
                'teachers_surplus' => 0,
                'faculty_rank_1' => 8,
                'faculty_rank_2' => 20,
                'faculty_rank_3' => 37,
                'faculty_doctors' => 4,
                'faculty_masters' => 45,
                'faculty_professors' => 0,
                'class_count' => 32,
                'classroom_count' => 30,
                'computer_room_count' => 4,
                'library' => true,
                'lab_count' => 6,
                'workshops_count' => 4,
                'campus_area_m2' => 35000,
                'partner_enterprises' => [],
                'gallery' => [
                    'https://images.unsplash.com/photo-1541339907198-e08756dedf3f?w=800&auto=format&fit=crop&q=80'
                ],
                'status' => 'VERIFIED'
            ],
            // GDTX TẠI HÀ NAM
            [
                'id' => 'HN-GDTX-001',
                'code' => '37110',
                'name' => 'Trung tâm GDTX - GDNN Tỉnh Hà Nam',
                'education_level_id' => 'gdtx',
                'school_type_id' => 'cong_lap',
                'ward' => 'Phường Phủ Lý',
                'legacy_province' => 'Hà Nam',
                'address' => 'Đường Trần Phú, Phường Quang Trung, TP. Phủ Lý, Tỉnh Hà Nam',
                'lat' => 20.532500,
                'lng' => 105.919800,
                'phone' => '0226 385 1245',
                'email' => 'ttgdtx.hanam@hanam.edu.vn',
                'website' => '',
                'principal' => 'Thầy Nguyễn Văn Tuấn',
                'leaders' => [
                    ['name' => 'Thầy Nguyễn Văn Tuấn', 'position' => 'Giám đốc Trung tâm'],
                    ['name' => 'Cô Lê Thị Tuyết', 'position' => 'Phó Giám đốc']
                ],
                'training_majors' => [
                    ['name' => 'Chương trình GDTX cấp THPT', 'degree_level' => 'trung_cap', 'major_code' => 'GDTX-THPT', 'annual_quota' => 350],
                    ['name' => 'Tin học ứng dụng & Chuyển đổi số', 'degree_level' => 'so_cap', 'major_code' => 'TH-VP', 'annual_quota' => 250],
                    ['name' => 'Tiếng Anh Giao tiếp cơ bản', 'degree_level' => 'so_cap', 'major_code' => 'NN-TA', 'annual_quota' => 200]
                ],
                'is_national_standard' => false,
                'national_standard_level' => null,
                'founded_year' => 1997,
                'student_count' => 850,
                'annual_enrollment' => 450,
                'annual_graduates' => 410,
                'employment_rate' => 89.0,
                'teacher_count' => 35,
                'teacher_quota' => 38,
                'teachers_shortage' => 3,
                'teachers_surplus' => 0,
                'faculty_rank_1' => 5,
                'faculty_rank_2' => 12,
                'faculty_rank_3' => 18,
                'faculty_doctors' => 1,
                'faculty_masters' => 22,
                'faculty_professors' => 0,
                'class_count' => 20,
                'classroom_count' => 18,
                'computer_room_count' => 4,
                'library' => true,
                'lab_count' => 2,
                'workshops_count' => 2,
                'campus_area_m2' => 12000,
                'partner_enterprises' => [],
                'gallery' => [
                    'https://images.unsplash.com/photo-1580582932707-520aed937b7b?w=800&auto=format&fit=crop&q=80'
                ],
                'status' => 'VERIFIED'
            ],
            [
                'id' => 'HN-GDTX-002',
                'code' => '37111',
                'name' => 'Trung tâm GDNN - GDTX Thị xã Duy Tiên',
                'education_level_id' => 'gdtx',
                'school_type_id' => 'cong_lap',
                'ward' => 'Phường Đồng Văn',
                'legacy_province' => 'Hà Nam',
                'address' => 'Phường Duy Tiên, Thị xã Duy Tiên, Tỉnh Hà Nam',
                'lat' => 20.627800,
                'lng' => 105.938500,
                'phone' => '0226 383 6128',
                'email' => 'gdnn.duytien@hanam.edu.vn',
                'website' => '',
                'principal' => 'Thầy Trần Mạnh Khang',
                'leaders' => [
                    ['name' => 'Thầy Trần Mạnh Khang', 'position' => 'Giám đốc']
                ],
                'training_majors' => [
                    ['name' => 'GDTX cấp THPT', 'degree_level' => 'trung_cap', 'major_code' => 'GDTX-THPT', 'annual_quota' => 280],
                    ['name' => 'May công nghiệp & Thời trang', 'degree_level' => 'so_cap', 'major_code' => 'MAY-CN', 'annual_quota' => 150],
                    ['name' => 'Vận hành máy cơ khí cơ bản', 'degree_level' => 'so_cap', 'major_code' => 'CK-VH', 'annual_quota' => 120]
                ],
                'is_national_standard' => false,
                'national_standard_level' => null,
                'founded_year' => 2002,
                'student_count' => 620,
                'annual_enrollment' => 320,
                'annual_graduates' => 290,
                'employment_rate' => 91.5,
                'teacher_count' => 28,
                'teacher_quota' => 30,
                'teachers_shortage' => 2,
                'teachers_surplus' => 0,
                'faculty_rank_1' => 3,
                'faculty_rank_2' => 10,
                'faculty_rank_3' => 15,
                'faculty_doctors' => 0,
                'faculty_masters' => 15,
                'faculty_professors' => 0,
                'class_count' => 16,
                'classroom_count' => 15,
                'computer_room_count' => 3,
                'library' => true,
                'lab_count' => 2,
                'workshops_count' => 3,
                'campus_area_m2' => 9800,
                'partner_enterprises' => [],
                'gallery' => [
                    'https://images.unsplash.com/photo-1524178232363-1fb2b075b655?w=800&auto=format&fit=crop&q=80'
                ],
                'status' => 'VERIFIED'
            ],
            [
                'id' => 'HN-GDTX-003',
                'code' => '37112',
                'name' => 'Trung tâm GDNN - GDTX Huyện Kim Bảng',
                'education_level_id' => 'gdtx',
                'school_type_id' => 'cong_lap',
                'ward' => 'Phường Kim Bảng',
                'legacy_province' => 'Hà Nam',
                'address' => 'Phường Kim Bảng, Tỉnh Hà Nam',
                'lat' => 20.578200,
                'lng' => 105.856400,
                'phone' => '0226 382 0145',
                'email' => 'gdnn.kimbang@hanam.edu.vn',
                'website' => '',
                'principal' => 'Thầy Đỗ Văn Chung',
                'leaders' => [
                    ['name' => 'Thầy Đỗ Văn Chung', 'position' => 'Giám đốc']
                ],
                'training_majors' => [
                    ['name' => 'GDTX cấp THPT', 'degree_level' => 'trung_cap', 'major_code' => 'GDTX-THPT', 'annual_quota' => 250],
                    ['name' => 'Kỹ thuật gò hàn cơ bản', 'degree_level' => 'so_cap', 'major_code' => 'HAN-CB', 'annual_quota' => 100],
                    ['name' => 'Sửa chữa xe gắn máy', 'degree_level' => 'so_cap', 'major_code' => 'XM-SC', 'annual_quota' => 80]
                ],
                'is_national_standard' => false,
                'national_standard_level' => null,
                'founded_year' => 2004,
                'student_count' => 510,
                'annual_enrollment' => 260,
                'annual_graduates' => 240,
                'employment_rate' => 88.0,
                'teacher_count' => 24,
                'teacher_quota' => 26,
                'teachers_shortage' => 2,
                'teachers_surplus' => 0,
                'faculty_rank_1' => 2,
                'faculty_rank_2' => 8,
                'faculty_rank_3' => 14,
                'faculty_doctors' => 0,
                'faculty_masters' => 12,
                'faculty_professors' => 0,
                'class_count' => 14,
                'classroom_count' => 12,
                'computer_room_count' => 2,
                'library' => true,
                'lab_count' => 1,
                'workshops_count' => 2,
                'campus_area_m2' => 8500,
                'partner_enterprises' => [],
                'gallery' => [
                    'https://images.unsplash.com/photo-1580582932707-520aed937b7b?w=800&auto=format&fit=crop&q=80'
                ],
                'status' => 'VERIFIED'
            ],
            [
                'id' => 'HN-GDTX-004',
                'code' => '37113',
                'name' => 'Trung tâm GDNN - GDTX Huyện Thanh Liêm',
                'education_level_id' => 'gdtx',
                'school_type_id' => 'cong_lap',
                'ward' => 'Xã Tân Thanh',
                'legacy_province' => 'Hà Nam',
                'address' => 'Xã Thanh Liêm, Tỉnh Hà Nam',
                'lat' => 20.486500,
                'lng' => 105.914200,
                'phone' => '0226 386 2154',
                'email' => 'gdnn.thanhliem@hanam.edu.vn',
                'website' => '',
                'principal' => 'Thầy Lê Văn Huynh',
                'leaders' => [
                    ['name' => 'Thầy Lê Văn Huynh', 'position' => 'Giám đốc']
                ],
                'training_majors' => [
                    ['name' => 'GDTX cấp THPT', 'degree_level' => 'trung_cap', 'major_code' => 'GDTX-THPT', 'annual_quota' => 220],
                    ['name' => 'Điện dân dụng & Công nghiệp', 'degree_level' => 'so_cap', 'major_code' => 'DIEN-DD', 'annual_quota' => 120]
                ],
                'is_national_standard' => false,
                'national_standard_level' => null,
                'founded_year' => 2005,
                'student_count' => 480,
                'annual_enrollment' => 240,
                'annual_graduates' => 220,
                'employment_rate' => 87.5,
                'teacher_count' => 22,
                'teacher_quota' => 25,
                'teachers_shortage' => 3,
                'teachers_surplus' => 0,
                'faculty_rank_1' => 2,
                'faculty_rank_2' => 7,
                'faculty_rank_3' => 13,
                'faculty_doctors' => 0,
                'faculty_masters' => 11,
                'faculty_professors' => 0,
                'class_count' => 12,
                'classroom_count' => 12,
                'computer_room_count' => 2,
                'library' => true,
                'lab_count' => 1,
                'workshops_count' => 2,
                'campus_area_m2' => 7800,
                'partner_enterprises' => [],
                'gallery' => [
                    'https://images.unsplash.com/photo-1524178232363-1fb2b075b655?w=800&auto=format&fit=crop&q=80'
                ],
                'status' => 'VERIFIED'
            ],
            [
                'id' => 'HN-GDTX-005',
                'code' => '37114',
                'name' => 'Trung tâm GDNN - GDTX Huyện Lý Nhân',
                'education_level_id' => 'gdtx',
                'school_type_id' => 'cong_lap',
                'ward' => 'Xã Bắc Lý',
                'legacy_province' => 'Hà Nam',
                'address' => 'Xã Nam Lý, Huyện Lý Nhân, Tỉnh Hà Nam',
                'lat' => 20.553200,
                'lng' => 106.071500,
                'phone' => '0226 387 0212',
                'email' => 'gdnn.lynhan@hanam.edu.vn',
                'website' => '',
                'principal' => 'Thầy Phạm Văn Quảng',
                'leaders' => [
                    ['name' => 'Thầy Phạm Văn Quảng', 'position' => 'Giám đốc']
                ],
                'training_majors' => [
                    ['name' => 'GDTX cấp THPT', 'degree_level' => 'trung_cap', 'major_code' => 'GDTX-THPT', 'annual_quota' => 260],
                    ['name' => 'Kỹ thuật Chế biến món ăn', 'degree_level' => 'so_cap', 'major_code' => 'NA-CB', 'annual_quota' => 140],
                    ['name' => 'Hàn cơ khí kết cấu', 'degree_level' => 'so_cap', 'major_code' => 'HAN-KC', 'annual_quota' => 100]
                ],
                'is_national_standard' => false,
                'national_standard_level' => null,
                'founded_year' => 2003,
                'student_count' => 540,
                'annual_enrollment' => 270,
                'annual_graduates' => 250,
                'employment_rate' => 90.0,
                'teacher_count' => 25,
                'teacher_quota' => 28,
                'teachers_shortage' => 3,
                'teachers_surplus' => 0,
                'faculty_rank_1' => 3,
                'faculty_rank_2' => 8,
                'faculty_rank_3' => 14,
                'faculty_doctors' => 0,
                'faculty_masters' => 13,
                'faculty_professors' => 0,
                'class_count' => 14,
                'classroom_count' => 14,
                'computer_room_count' => 2,
                'library' => true,
                'lab_count' => 2,
                'workshops_count' => 2,
                'campus_area_m2' => 8200,
                'partner_enterprises' => [],
                'gallery' => [
                    'https://images.unsplash.com/photo-1580582932707-520aed937b7b?w=800&auto=format&fit=crop&q=80'
                ],
                'status' => 'VERIFIED'
            ],
            [
                'id' => 'HN-GDTX-006',
                'code' => '37115',
                'name' => 'Trung tâm GDNN - GDTX Huyện Bình Lục',
                'education_level_id' => 'gdtx',
                'school_type_id' => 'cong_lap',
                'ward' => 'Xã Bình Mỹ',
                'legacy_province' => 'Hà Nam',
                'address' => 'Phường Hà Nam, Tỉnh Hà Nam',
                'lat' => 20.514500,
                'lng' => 106.012500,
                'phone' => '0226 386 0341',
                'email' => 'gdnn.binhluc@hanam.edu.vn',
                'website' => '',
                'principal' => 'Thầy Hoàng Văn Nam',
                'leaders' => [
                    ['name' => 'Thầy Hoàng Văn Nam', 'position' => 'Giám đốc']
                ],
                'training_majors' => [
                    ['name' => 'GDTX cấp THPT', 'degree_level' => 'trung_cap', 'major_code' => 'GDTX-THPT', 'annual_quota' => 240],
                    ['name' => 'Điện cơ & Quấn máy', 'degree_level' => 'so_cap', 'major_code' => 'DC-QM', 'annual_quota' => 100],
                    ['name' => 'Lái xe ô tô hạng B2, C', 'degree_level' => 'so_cap', 'major_code' => 'LX-B2', 'annual_quota' => 150]
                ],
                'is_national_standard' => false,
                'national_standard_level' => null,
                'founded_year' => 2004,
                'student_count' => 520,
                'annual_enrollment' => 260,
                'annual_graduates' => 245,
                'employment_rate' => 89.5,
                'teacher_count' => 24,
                'teacher_quota' => 26,
                'teachers_shortage' => 2,
                'teachers_surplus' => 0,
                'faculty_rank_1' => 2,
                'faculty_rank_2' => 8,
                'faculty_rank_3' => 14,
                'faculty_doctors' => 0,
                'faculty_masters' => 12,
                'faculty_professors' => 0,
                'class_count' => 14,
                'classroom_count' => 13,
                'computer_room_count' => 2,
                'library' => true,
                'lab_count' => 1,
                'workshops_count' => 2,
                'campus_area_m2' => 8000,
                'partner_enterprises' => [],
                'gallery' => [
                    'https://images.unsplash.com/photo-1524178232363-1fb2b075b655?w=800&auto=format&fit=crop&q=80'
                ],
                'status' => 'VERIFIED'
            ],

            // ==============================================================
            // CÁC TRƯỜNG NÒNG CỐT NINH BÌNH
            // ==============================================================
            [
                'id' => 'NB-GDTX-001',
                'code' => '37023',
                'name' => 'Trung tâm GDTX - Tin học Ngoại ngữ Tỉnh Ninh Bình',
                'education_level_id' => 'gdtx',
                'school_type_id' => 'cong_lap',
                'ward' => 'Phường Hoa Lư',
                'legacy_province' => 'Ninh Bình',
                'address' => 'Số 12 Đường Lê Thái Tổ, TP. Ninh Bình',
                'lat' => 20.264500,
                'lng' => 105.973000,
                'phone' => '0229 387 1515',
                'email' => 'ttgdtx.tinh@ninhbinh.edu.vn',
                'website' => 'http://gdtxninhbinh.edu.vn',
                'principal' => 'Thầy Nguyễn Đăng Khánh',
                'leaders' => [
                    ['name' => 'Thầy Nguyễn Đăng Khánh', 'position' => 'Giám đốc Trung tâm'],
                    ['name' => 'Cô Trần Thị Mai', 'position' => 'Phó Giám đốc'],
                    ['name' => 'ThS. Đỗ Văn Nam', 'position' => 'Trưởng phòng Đào tạo & Bồi dưỡng']
                ],
                'training_majors' => [
                    ['name' => 'Chương trình GDTX cấp THPT', 'degree_level' => 'trung_cap', 'major_code' => 'GDTX-THPT', 'annual_quota' => 250],
                    ['name' => 'Tin học Văn phòng Ứng dụng', 'degree_level' => 'so_cap', 'major_code' => 'TH-VP', 'annual_quota' => 200],
                    ['name' => 'Tiếng Anh Giao tiếp Khung chuẩn', 'degree_level' => 'so_cap', 'major_code' => 'NN-TA', 'annual_quota' => 180]
                ],
                'is_national_standard' => false,
                'national_standard_level' => null,
                'founded_year' => 1993,
                'student_count' => 680,
                'annual_enrollment' => 420,
                'annual_graduates' => 390,
                'employment_rate' => 88.0,
                'teacher_count' => 42,
                'teacher_quota' => 45,
                'teachers_shortage' => 3,
                'teachers_surplus' => 0,
                'faculty_rank_1' => 4,
                'faculty_rank_2' => 12,
                'faculty_rank_3' => 26,
                'faculty_doctors' => 2,
                'faculty_masters' => 18,
                'faculty_professors' => 0,
                'class_count' => 16,
                'classroom_count' => 18,
                'computer_room_count' => 4,
                'library' => true,
                'lab_count' => 1,
                'workshops_count' => 4,
                'campus_area_m2' => 12500,
                'partner_enterprises' => [
                    ['name' => 'Viettel Telecom Ninh Bình', 'cooperation' => 'Hợp tác đào tạo tin học ứng dụng và thực tập sinh', 'logo' => 'https://images.unsplash.com/photo-1549399542-7e3f8b79c341?w=200&auto=format&fit=crop&q=80', 'is_featured' => true],
                    ['name' => 'VNPT Ninh Bình', 'cooperation' => 'Tài trợ phòng máy tính và cấp chứng chỉ CNTT', 'logo' => 'https://images.unsplash.com/photo-1581091226825-a6a2a5aee158?w=200&auto=format&fit=crop&q=80', 'is_featured' => true]
                ],
                'gallery' => [
                    'https://images.unsplash.com/photo-1580582932707-520aed937b7b?w=800&auto=format&fit=crop&q=80',
                    'https://images.unsplash.com/photo-1524178232363-1fb2b075b655?w=800&auto=format&fit=crop&q=80'
                ],
                'status' => 'VERIFIED'
            ],
            [
                'id' => 'NB-CD-001',
                'code' => '37010',
                'name' => 'Trường Cao đẳng Cơ điện Xây dựng Việt Xô',
                'education_level_id' => 'cao_dang',
                'school_type_id' => 'cong_lap',
                'ward' => 'Phường Trung Sơn',
                'legacy_province' => 'Ninh Bình',
                'address' => 'Số 1 Đường Lam Sơn, Phường Tây Sơn, TP. Tam Điệp',
                'lat' => 20.144800,
                'lng' => 105.895500,
                'phone' => '0229 386 4141',
                'email' => 'vietxo@cdvietxo.edu.vn',
                'website' => 'https://cdvietxo.edu.vn',
                'principal' => 'TS. Phạm Ngọc Vũ',
                'leaders' => [
                    ['name' => 'TS. Phạm Ngọc Vũ', 'position' => 'Hiệu trưởng'],
                    ['name' => 'ThS. Nguyễn Thị Lan', 'position' => 'Phó Hiệu trưởng phụ trách Đào tạo'],
                    ['name' => 'ThS. Trần Mạnh Hùng', 'position' => 'Phó Hiệu trưởng phụ trách NCKH'],
                    ['name' => 'KS. Lê Văn Thắng', 'position' => 'Trưởng khoa Cơ khí Ô tô'],
                    ['name' => 'ThS. Vũ Hoàng Điệp', 'position' => 'Trưởng khoa Điện - Điện tử']
                ],
                'training_majors' => [
                    ['name' => 'Công nghệ Kỹ thuật Ô tô', 'degree_level' => 'cao_dang', 'major_code' => '6510216', 'annual_quota' => 350],
                    ['name' => 'Điện công nghiệp & Dân dụng', 'degree_level' => 'cao_dang', 'major_code' => '6520227', 'annual_quota' => 280],
                    ['name' => 'Hàn công nghệ cao', 'degree_level' => 'trung_cap', 'major_code' => '5520123', 'annual_quota' => 200],
                    ['name' => 'Vận hành Máy thi công xây dựng', 'degree_level' => 'trung_cap', 'major_code' => '5580201', 'annual_quota' => 180],
                    ['name' => 'Kỹ thuật Lắp đặt Điện & Điều hòa', 'degree_level' => 'so_cap', 'major_code' => '4520202', 'annual_quota' => 150]
                ],
                'is_national_standard' => true,
                'national_standard_level' => 2,
                'founded_year' => 1978,
                'student_count' => 2400,
                'annual_enrollment' => 1150,
                'annual_graduates' => 980,
                'employment_rate' => 94.5,
                'teacher_count' => 145,
                'teacher_quota' => 150,
                'teachers_shortage' => 5,
                'teachers_surplus' => 0,
                'faculty_rank_1' => 10,
                'faculty_rank_2' => 20,
                'faculty_rank_3' => 85,
                'faculty_doctors' => 11,
                'faculty_masters' => 11,
                'faculty_professors' => 2,
                'class_count' => 65,
                'classroom_count' => 55,
                'computer_room_count' => 6,
                'library' => true,
                'lab_count' => 12,
                'workshops_count' => 16,
                'campus_area_m2' => 48000,
                'partner_enterprises' => [
                    ['name' => 'Tập đoàn Hyundai Thành Công Ninh Bình', 'cooperation' => 'Hợp tác đào tạo thực tập & tuyển dụng kỹ sư công nghệ ô tô', 'logo' => 'https://images.unsplash.com/photo-1549399542-7e3f8b79c341?w=200&auto=format&fit=crop&q=80', 'is_featured' => true],
                    ['name' => 'Tổng công ty LILAMA Ninh Bình', 'cooperation' => 'Đào tạo kỹ sư cơ khí lắp máy & hàn công nghệ cao', 'logo' => 'https://images.unsplash.com/photo-1504917599217-d4dc5ebe6122?w=200&auto=format&fit=crop&q=80', 'is_featured' => true],
                    ['name' => 'Công ty TNHH Mcnex Vina Ninh Bình', 'cooperation' => 'Cung ứng nhân lực kỹ thuật điện tử công nghệ cao', 'logo' => 'https://images.unsplash.com/photo-1581091226825-a6a2a5aee158?w=200&auto=format&fit=crop&q=80', 'is_featured' => true],
                    ['name' => 'Tập đoàn Xi măng The Vissai', 'cooperation' => 'Hợp tác vận hành hệ thống điện và máy công nghiệp', 'logo' => 'https://images.unsplash.com/photo-1486406146926-c627a92ad1ab?w=200&auto=format&fit=crop&q=80', 'is_featured' => true],
                    ['name' => 'Công ty Doosan Vina Hải Phòng', 'cooperation' => 'Tài trợ xưởng thực hành và tuyển dụng học viên tốt nghiệp', 'logo' => 'https://images.unsplash.com/photo-1563986768609-322da13575f3?w=200&auto=format&fit=crop&q=80', 'is_featured' => true]
                ],
                'gallery' => [
                    'https://images.unsplash.com/photo-1562774053-701939374585?w=800&auto=format&fit=crop&q=80',
                    'https://images.unsplash.com/photo-1581092160607-ee22621dd758?w=800&auto=format&fit=crop&q=80',
                    'https://images.unsplash.com/photo-1581092335397-9583fe92d232?w=800&auto=format&fit=crop&q=80',
                    'https://images.unsplash.com/photo-1523240795612-9a054b0db644?w=800&auto=format&fit=crop&q=80',
                    'https://images.unsplash.com/photo-1541339907198-e08756dedf3f?w=800&auto=format&fit=crop&q=80'
                ],
                'status' => 'VERIFIED'
            ],
            [
                'id' => 'NB-CD-002',
                'code' => '37022',
                'name' => 'Trường Cao đẳng Y tế Ninh Bình',
                'education_level_id' => 'cao_dang',
                'school_type_id' => 'cong_lap',
                'ward' => 'Phường Hoa Lư',
                'legacy_province' => 'Ninh Bình',
                'address' => 'Số 293 Đường Hải Thượng Lãn Ông, TP. Ninh Bình',
                'lat' => 20.237200,
                'lng' => 105.964800,
                'phone' => '0229 387 1045',
                'email' => 'cdytenb@ninhbinh.edu.vn',
                'website' => 'http://cdyteninhbinh.edu.vn',
                'principal' => 'TS. Bác sĩ Trần Ngọc Trung',
                'leaders' => [
                    ['name' => 'TS. Bác sĩ Trần Ngọc Trung', 'position' => 'Hiệu trưởng'],
                    ['name' => 'ThS. Nguyễn Văn Bình', 'position' => 'Phó Hiệu trưởng']
                ],
                'training_majors' => [
                    ['name' => 'Điều dưỡng Đa khoa', 'degree_level' => 'cao_dang', 'major_code' => '6720301', 'annual_quota' => 300],
                    ['name' => 'Dược sĩ Cao đẳng', 'degree_level' => 'cao_dang', 'major_code' => '6720201', 'annual_quota' => 250]
                ],
                'is_national_standard' => true,
                'national_standard_level' => 2,
                'founded_year' => 1964,
                'student_count' => 1850,
                'annual_enrollment' => 800,
                'annual_graduates' => 750,
                'employment_rate' => 95.0,
                'teacher_count' => 112,
                'teacher_quota' => 120,
                'teachers_shortage' => 8,
                'teachers_surplus' => 0,
                'faculty_rank_1' => 14,
                'faculty_rank_2' => 28,
                'faculty_rank_3' => 70,
                'faculty_doctors' => 12,
                'faculty_masters' => 68,
                'faculty_professors' => 1,
                'class_count' => 48,
                'classroom_count' => 40,
                'computer_room_count' => 4,
                'library' => true,
                'lab_count' => 8,
                'workshops_count' => 0,
                'campus_area_m2' => 31000,
                'partner_enterprises' => [],
                'gallery' => [
                    'https://images.unsplash.com/photo-1581092160607-ee22621dd758?w=800&auto=format&fit=crop&q=80'
                ],
                'status' => 'VERIFIED'
            ],
            [
                'id' => 'NB-DH-001',
                'code' => '37024',
                'name' => 'Trường Đại học Hoa Lư',
                'education_level_id' => 'dai_hoc',
                'school_type_id' => 'cong_lap',
                'ward' => 'Phường Hoa Lư',
                'legacy_province' => 'Ninh Bình',
                'address' => 'Khu đô thị Xuân Thành, TP. Ninh Bình',
                'lat' => 20.267500,
                'lng' => 105.952000,
                'phone' => '0229 389 2244',
                'email' => 'contact@hluv.edu.vn',
                'website' => 'https://hluv.edu.vn',
                'principal' => 'PGS.TS. Vũ Văn Hùng',
                'leaders' => [
                    ['name' => 'PGS.TS. Vũ Văn Hùng', 'position' => 'Hiệu trưởng'],
                    ['name' => 'TS. Nguyễn Thị Thúy', 'position' => 'Phó Hiệu trưởng']
                ],
                'training_majors' => [
                    ['name' => 'Sư phạm Tiểu học', 'degree_level' => 'dai_hoc', 'major_code' => '7140202', 'annual_quota' => 300],
                    ['name' => 'Sư phạm Mầm non', 'degree_level' => 'dai_hoc', 'major_code' => '7140201', 'annual_quota' => 250],
                    ['name' => 'Quản trị Dịch vụ Du lịch & Lữ hành', 'degree_level' => 'dai_hoc', 'major_code' => '7810103', 'annual_quota' => 250],
                    ['name' => 'Công nghệ Thông tin', 'degree_level' => 'dai_hoc', 'major_code' => '7480201', 'annual_quota' => 200]
                ],
                'is_national_standard' => true,
                'national_standard_level' => 2,
                'founded_year' => 2007,
                'student_count' => 3500,
                'annual_enrollment' => 1200,
                'annual_graduates' => 1050,
                'employment_rate' => 93.0,
                'teacher_count' => 210,
                'teacher_quota' => 220,
                'teachers_shortage' => 10,
                'teachers_surplus' => 0,
                'faculty_rank_1' => 30,
                'faculty_rank_2' => 60,
                'faculty_rank_3' => 120,
                'faculty_doctors' => 35,
                'faculty_masters' => 140,
                'faculty_professors' => 3,
                'class_count' => 80,
                'classroom_count' => 70,
                'computer_room_count' => 8,
                'library' => true,
                'lab_count' => 10,
                'workshops_count' => 0,
                'campus_area_m2' => 85000,
                'partner_enterprises' => [],
                'gallery' => [
                    'https://images.unsplash.com/photo-1562774053-701939374585?w=800&auto=format&fit=crop&q=80'
                ],
                'status' => 'VERIFIED'
            ]
        ];

        foreach ($schools as $data) {
            $levelId = $data['education_level_id'];
            $data['geom'] = DB::raw("Point({$data['lng']}, {$data['lat']})");
            $school = School::updateOrCreate(
                ['id' => $data['id']],
                $data
            );
            $school->educationLevels()->sync([$levelId]);
        }

        $this->command->info('Đã nhập thành công ' . count($schools) . ' trường học (bao gồm khu vực Hà Nam & Ninh Bình)!');
    }
}
